color_dictionary = {"light blue": "tab:blue",
                    "orange": "tab:orange",
                    "green": "tab:green",
                    "dark red": "tab:red",
                    "purple": "tab:purple",
                    "brown": "tab:brown",
                    "pink": "tab:pink",
                    "grey": "tab:gray",
                    "olive": "tab:olive",
                    "cyan": "tab:cyan",
                    "dark blue": "b",
                    "dark green": "g",
                    "red": "r",
                    "magenta": "m",
                    "black": "k",
                    }
